version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - CLIP_MODEL_NAME=openai/clip-vit-base-patch16
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    image: streamlit:latest
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: streamlit run app.py --server.port=8501
    depends_on:
      - backend
    environment:
      - STREAMLIT_SERVER_PORT=8501
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
